# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs the Gradle build task, but without running the JUnit tests
      - name: Run the Gradle Build
        run: ./gradlew build -x test

      # Builds a 'fat' jar file with the dependencies from Gradle
      - name: Archive Jar with Dependencies
        uses: actions/upload-artifact@v2
        with:
          name: Jar with Dependencies
          path: build/libs

